nelmio_api_doc:
    documentation:
        info:
            title: API app.
            description: exists for no reason!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

        paths:
            /api/login_check:
                post:
                    tags:
                        - Authentication
                    summary: Login check
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            example: vasya@pupkin.org
                                        password:
                                            type: string
                                            example: 1234qwerty
                    responses:
                        "200":
                            description: Login successful
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        "401":
                            description: Invalid credentials

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc($|\.)) # Accepts routes under /api except /api/doc
